### PR TITLE
Add objectKeyValues, fix #29

### LINKED ISSUE #29: objectKeyValues :: (Text -> Parser a) -> Parser a
It would be nice to have an object parser that lets you dynamically parse each element of an object based on its key, like:
```
objectKeyValues :: (Text -> Parser a) -> Parser a
```
This is a generalization of the other object parsers and looks like it should be fairly easy.

### PR DESCRIPTION
**Pull request by dylex**
As described in #29. Totally open to feedback on name/implementation.

### CODE REVIEW

**Comment by ondrap** [comment]
Looks good, do you think you could add a one or two lines to tests?

**Comment by dylex** [comment]
Sure, added a simple test, thanks!

By the way, by switching from aeson to json-stream for our ES query parsing, we improved overall performance by about 30%, and based on profiling the cost of parsing dropped about 4x (such that it's no longer the most expensive thing we do).

**Comment by ondrap** [comment]
Could you try the latest master from this repo? I have just pushed one small optimization and it seems to me it's quite significant.

**Comment by dylex** [comment]
I maybe see a very slight improvement but not much.  However, we have almost exclusively numeric data, very few strings.

**Comment by ondrap** [comment]
Yes, it's an improvement when strings are used. I'm merging this and I'll release a new version.

**Pull request merged**
